[project]
name = "cryosim-recon"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Thomas Fish", email = "thomas.fish@diamond.ac.uk" },
]
dependencies = [
    "pycudasirecon ~= 0.1.0",
    "mrcfile ~= 1.5.0",
    "numpy ~= 1.26.4",
    "ome-types >=0.5.1, <=0.6",
    "tifffile >=2024.2.12",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [
    "src/cryosim_recon",
]
