name: Generate README
on:
  workflow_call:
    inputs:
      git_ref:
        description: "Git reference to use for checks"
        type: string

jobs:
  make-README:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
          sparse-checkout: |
            README.md
            docs
            releng

      - name: Fill template
        run: |
          ./releng/README_from_docs.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: Automated update of README.md from docs
