name: Trigger docs generation
on:
  push:
    branches:
      - merge-action-test

jobs:
  check-changes:
    # Check changes against the most recent commit on the same branch before the push
    runs-on: ubuntu-latest
    outputs:
      docs-changed: ${{ steps.filter.outputs.docs }}
      parser-changed: ${{ steps.filter.outputs.parser }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**/*'
            parser:
              - 'src/sim_recon/cli/parsing/*'
              - 'src/sim_recon/settings/formatting.py'
  generate-help-docs:
    needs: check-changes
    if: needs.check-changes.outputs.parser-changed == 'true'
    uses: ./.github/workflows/generate_help_docs.yaml
  generate-README:
    needs: [check-changes, generate-help-docs]
    if: always() && !cancelled() && (needs.check-changes.outputs.docs-changed == 'true' || needs.generate-help-docs.outputs.changes_detected == 'true')
    uses: ./.github/workflows/generate_README.yaml
