name: Trigger docs generation
on: pull_request

jobs:
  check-parser-paths:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.parser }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            parser:
              - 'src/sim_recon/cli/parsing/*'
              - 'src/sim_recon/settings/formatting.py'
  generate-help-docs:
    needs: check-parser-paths
    if: needs.check-parser-paths.outputs.changed == 'true'
    uses: ./.github/workflows/generate_help_docs.yaml
  check-docs-paths: # Checking this after generate-help-docs ensures changes made by that workflow are found
    runs-on: ubuntu-latest
    needs: generate-help-docs
    if: always() && !cancelled() # Should be run after generate-help-docs, regardless of the result
    outputs:
      changed: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**/*'
  generate-README:
    needs: check-docs-paths
    if: always() && !cancelled() && needs.check-docs-paths.outputs.changed == 'true'
    uses: ./.github/workflows/generate_README.yaml
